# Generated by Django 4.2.4 on 2023-08-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-booking_date", "-booking_time"]},
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_notes",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="timestamp_booking_made",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
